@extends('layouts.app')
    @section('content')
   
     <div class="card mb-4 w-100" style="">
                    <div class="card-header">
                        <h3 class="mr-3 text-center" > Conditions générales d'utilisations.</h3>
                    </div>
                    <div class="card-body">
<h4>1. CONSENTEMENT </h4><br>                       


<h6 style="font-weight: initial;" class="text-justify"><span style="color:#1E90FF;">MAKI-IMMO.COM</span> fournit des ressources en ligne qui comprennent des petites annonces, des services de mise en réseau social et plusieurs services de courriels (ci-après, les « Services ») soumis aux Conditions d’Utilisation (ci-après « Conditions »).<BR> Lorsque vous utilisez ce site, vous acceptez d’être lié par les termes et conditions énoncés dans le présent document. <BR>De plus, lorsque vous utilisez un service particulier de <span style="color:#1E90FF;">MAKI-IMMO.COM</span>, vous consentez à respecter les règles publiées pour tous les services <span style="color:#1E90FF;">MAKI-IMMO.COM</span> applicables et qui sont susceptibles d’être modifiés.<BR> En cas de désaccord avec les termes de ces Conditions, les modifications réalisées a posteriori ou si vous n’êtes pas satisfait par les services fournis, la seule solution consiste à ne plus utiliser <span style="color:#1E90FF;">MAKI-IMMO.COM</span>. <BR>Ces Conditions sont susceptibles d’être mises à jour à n’importe quel moment.<BR> Vous déclarez comprendre et connaître votre obligation à vérifier régulièrement les possibles modifications portées à ces Conditions. <BR> <span style="color:#1E90FF;">MAKI-IMMO.COM</span> s’engage à communiquer à travers le site <span style="color:#1E90FF;">MAKI-IMMO.COM</span> toute modification importante réalisée à ces Conditions.</h6><br>



<h4>2. Création de compte</h4><br>

<h6>Vous déclarez comprendre que tous les messages, les commentaires, les fichiers, les images, les photos, les vidéos, les sons et tout autre matériel (« Contenu ») envoyé, transmis ou relié au Service relèvent de la responsabilité de la personne à l’origine de ce Contenu. <BR>Concrètement, vous serez tenu responsable de tous les Contenus que vous téléchargez, envoyez ou distribuez à travers les Services.<BR> Vous déclarer comprendre que ne contrôle pas <span style="color:#1E90FF;">MAKI-IMMO.COM</span> et ne peut être tenu responsable du Contenu distribué à travers le site Internet et que, lorsque vous utilisez le site, vous pourrez vous trouver face a des Contenus offensifs, déplacés, indécents ou choquants.<BR> De plus, le site <span style="color:#1E90FF;"><span style="color:#1E90FF;">MAKI-IMMO.COM</span></span> et les Contenus publiés à travers son site sont susceptibles de comporter des liens vers d’autres sites Internet qui n’ont aucune relation avec <span style="color:#1E90FF;">MAKI-IMMO.COM</span>.<BR> <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne peut aucunement garantir la véracité ou l’authenticité des informations contenues sur de tels sites.<BR> Si vous vous redirigez vers d’autres sites Internet, vous le ferez à vos propres risques.<BR> Vous reconnaissez que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> n’effectue pas de prévisualisation ni n’approuve le Contenu avant sa publication. <BR>Toutefois <span style="color:#1E90FF;">MAKI-IMMO.COM</span> se réserve le droit de refuser, supprimer ou déplacer tout Contenu distribué à travers du Service qui contrevienne à l’esprit du site ou enfreigne les Conditions.   </h6><br>
     
<h4>3. CONDUITE</h4><br>

<h6 style="font-weight: initial;" class="text-justify">
 <h5 style="font-weight: bold;">Vous vous engagez à ne pas distribuer ni envoyer les Contenus :</h5>
<span style="font-weight: bold;">a.</span> Contrevenant aux lois en vigueur,<br>
<span style="font-weight: bold;">b.</span> Nuisibles, illicites, dangereux, abusifs, calomnieux, pornographiques, diffamatoires, portant atteinte à la vie privée ou susceptibles de nuire aux enfants;<br>
<span style="font-weight: bold;">c.</span> Qui harcèlent, dégradent, intimident ou de caractères haineux envers un individu ou un groupe en raison de sa religion, son sexe, son orientation sexuelle, sa race, son appartenance ethnique, son âge ou son handicap;<br>
<span style="font-weight: bold;">d.</span> Usurpant l’identité d’un tiers, y compris (mais non limité à) les employés de MAKI-IMMO.COM;<br>
<span style="font-weight: bold;">e.</span> Contenant des informations personnelles appartenant à une autre personne et sans son consentement;<br>
<span style="font-weight: bold;">f.</span> Faux, trompeurs, fallacieux, cherchant à désinforment ou à faire diversion;<br>
<span style="font-weight: bold;">g.</span> Contrevenant aux termes d’un brevet d’invention, marque enregistrée, secret commercial, droit d’auteur ou d’autre droit de propriété de toute autre personne, ou Contenu dont l’Utilisateur n’a pas le droit de mettre à disposition du public conformément à une disposition légale, à une relation contractuelle.<br>
<span style="font-weight: bold;">h.</span> Représentant ou contenant une forme de marketing d’affiliation, code de référencement, « junk mail » ou « spam », lettres chaîne, marketing pyramidal ou de publicité non sollicitée.<br>
<span style="font-weight: bold;">i.</span> Représentant ou contenant une forme de publicité ou de sollicitation si (1) ce Contenu est placé dans une section ou une catégorie non destinées à de telles fins; ou (2) si ce Contenu est envoyé par courriel aux utilisateurs de MAKI-IMMO.COM qui avaient demandé à ne pas recevoir d’informations commerciales;<br>
<span style="font-weight: bold;">j.</span> Contenant des liens vers des services commerciaux ou des sites Internet, sauf les cas clairement définis par MAKI-IMMO.COM ;<br>
<span style="font-weight: bold;">k.</span> Promotionnant des services illicites ou proposant des produits dont la vente est interdite ou réglementée par la législation en vigueur, y compris tous les articles dont la vente est interdite ou réglementée par la loi sénégalaise;<br>
<span style="font-weight: bold;">l.</span> Contenant des virus informatiques ou tout autre code informatique, les fichiers et les programmes destinés à détruire ou diminuer le bon fonctionnement de n’importe quel équipement informatique (logiciel ou hardware) ou de télécommunication;<br>
<span style="font-weight: bold;">m.</span> Qui interrompent les connexions normales en envoyant un nombre excessif de messages au Service (flooding attack) ou qui interrompent en général l’accès normal des usagers au Service;<br>
<span style="font-weight: bold;">n.</span> Qui utilisent de fausses adresses email ou de fausses en-têtes ou manipulent de façon générale les identifiants afin de dissimuler l’origine du Contenu transmis via le Service.<br>
<h5 style="font-weight: bold;">De plus, vous vous compromettez à ne pas :</h5>
a. Prendre contact avec des personnes qui n’ont pas demandé à être contactées;<br>
b. Poursuivre ni harceler personne;<br>
c. Recueillir des informations personnelles concernant d’autres usagers à des fins commerciales ou illégales;<br>
d. Avoir recours à des moyens automatiques tels que des robots, des outils d’exploration des données, etc. pour télécharger des données depuis le Service – à l’exception des moteurs de recherche (par ex. Google) et des archives publiques non commerciales (par ex. archive.org) qui sont conformes à nos fichiers robots.txt;<br>
e. Publier de Contenu global ou hors de propos, publier continuellement le même Contenu ou faire supporter un poids disproportionné à notre infrastructure;<br>
f. Publier le même article ou service dans plus d’une catégorie, ou sous-catégorie.<br>
g. Tenter d’accéder aux systèmes informatiques de MAKI-IMMO.COM ou tenter d’une façon ou d’une autre d’interrompre, de diminuer, de nuire au fonctionnement de, ou de détériorer le Service ou le site Internet de MAKI-IMMO.COM.<br>
</h6><br>



<h4>4. CONFIDENTIALITÉ ET INFORMATION DU PUBLIC</h4><br>

<h6>Lorsque vous utilisez le site de <span style="color:#1E90FF;">MAKI-IMMO.COM</span> vous déclarez et vous engagez à ce que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> conserve ou divulgue, à son entière discrétion, votre Contenu ou vos données, telles que les adresses email et IP, l’horodatage ou toute autre information concernant l’utilisateur, si exigé par la loi ou si, agissant de bonne foi, la préservation ou la divulgation est considérée dans ces cas comme nécessaires afin de : suivre des procédures légales; appliques ces Conditions; veiller à ce qu’aucun Contenu ne viole les droits de tierces parties; veiller à ce qu’aucune information de contact (par ex. numéro de téléphone, adresse du domicile) de tiers n’est publiée ou transmise sans leur consentement ou dans des cas de harcèlement; veiller à la protection des droits et à la sécurité des biens et des personnes tant pour <span style="color:#1E90FF;">MAKI-IMMO.COM</span> que pour ses usagers ou le grand public.    </h6><br>     

     
<h4>5. NOTIFICATION DES AVIS D’INFRACTION</h4><br>

<h6>Si vous pensez que votre travail a été copié et que l’on a porté atteinte à votre droit d’auteur ou à vos droits de propriété intellectuelle, veuillez nous contacter à partir de la page « Contact ».<br>
A cette fin, veuillez fournir à nos représentants les indications suivantes :
a. Identifiez le contenu sur le site <span style="color:#1E90FF;">MAKI-IMMO.COM</span> qui, selon vous, viole vos droits, en n’oubliant pas de donner suffisamment d’indications afin que nous puissions le localiser sur notre site;<br>
b. Une déclaration faite en votre nom indiquant que vous disposez de raisons suffisantes pour prouver que le contenu litigieux n’a pas l’accord de son auteur ni de son agent et enfreint la loi;<br>
c. Une déclaration faite en votre nom (1) assurant que les informations présente dans votre déclaration sont fiables et (2) démontrant que vous êtes propriétaire du droit d’auteur en question ou êtes autorisé à agir en son nom;<br>
d. Votre adresse, votre numéro de téléphone et votre adresse email; <br>
e. Votre signature physique ou électronique.<br>
Nous nous réservons le droit de retirer les contenus lorsque nous soupçonnons toute enfreinte à ces conditions ou toute violation des droits.<br>
.</h6><br>



 <h4>6. PRATIQUES CONTRE LE « SPAM »</h4><br>
 <h6>Vous convenez et acceptez que l’envoi non sollicité de messages publicitaires à des adresses email de <span style="color:#1E90FF;"><span style="color:#1E90FF;">MAKI-IMMO.COM</span></span> ou via les systèmes informatiques de <span style="color:#1E90FF;">MAKI-IMMO.COM</span>, est expressément interdit par ces Conditions.<br> Toute utilisation frauduleuse des systèmes informatiques de MAKI-IMMO.COM sera considérée comme une enfreinte aux Conditions présentées par ce document et à la législation sénégalaise. <br>De telles enfreintes sont susceptibles d’exposer le responsable ou ses représentants à des poursuites civiles et pénales. </h6><br>


 <h4>7. TRANSACTIONS AVEC LES PERSONNES PHYSIQUES ET JURIDIQUES</h4><br>
<h6><span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne pourra être tenu responsable de votre interaction avec des personnes juridiques et/ou physiques initiées sur le Site ou à travers le Service. <br>Ceci comprend, sans y être limité, le paiement et la livraison de biens et services, et tout autre terme, condition, garanties ou représentations y ayant trait.<br> Ces transactions s’effectueront uniquement entre vous et ces personnes physiques ou juridiques.
Vous convenez et acceptez que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne serait être tenu responsable ou passible de poursuites pour la perte ou les dommages encourus au cours de telles transactions. En cas de querelle entre des usagers du site ou entre un usager et un tiers, vous convenez et acceptez que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> n’est soumis à aucune obligation d’intervenir. <br>Dans le cas où surgisse une querelle entre plusieurs usagers, vous reconnaissez dégager <span style="color:#1E90FF;">MAKI-IMMO.COM</span>, ses agents, employés, représentants et ayant droits de toute responsabilité sur les plaintes et les dommages (directs et indirects) de toute sorte ou nature, connu et à connaître, soupçonnés ou non, déclarés ou non, résultant ou ayant trait à ces querelles et/ou nos services.
. </h6>
<h4>8. LIMITES ET RÉSILIATION DU SERVICE</h4><br>
 <h6>Vous convenez et reconnaissez que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> peut établir des limites concernant l’utilisation faite de son Service, concernant entre autre le nombre maximal de jours durant lesquels le Contenu sera retenu par le Service, le nombre et la taille maximale des messages ou d’autre Contenu transmis ou stockés par le Service, et la fréquence d’accès au Service.<br> Vous convenez que la responsabilité de <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne pourra être engagée en cas de suppression ou d’incapacité à enregistrer un Contenu conservé ou transmis par le Service.<br> Vous convenez que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> se réserve le droit de modifier ou d’interrompre à tout moment le Service (ou partie de celui-ci) sans obligation d’en avertir, et que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> n’est astreint à aucune obligation concernant la modification, la suspension ou l’interruption du Service.<br>
Vous convenez et acceptez que MAKI-IMMO.COM a le droit (mais pas l’obligation) de supprimer ou de désactiver un compte, de bloquer un email ou une adresse IP ou de suspendre votre accès au Service (ou partie de celui-ci), de façon immédiate et sans préavis, et à son entière discrétion, et de supprimer ou de rejeter tout Contenu au sein du Service, sans en communiquer la raison et sans limitation, si <span style="color:#1E90FF;">MAKI-IMMO.COM</span> soupçonne que vous avez manqué au texte ou à l’esprit des Conditions d’Utilisation. De plus, vous convenez que la responsabilité de <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne pourra être engagée en cas de résiliation de votre accès au Service.<br> Vous acceptez également de ne pas tenter d’utiliser le Service après résiliation.
. </h6><br>
 <h4>9. PRATIQUES CONTRE LE « SPAM »</h4><br>
 <h6>Vous convenez et acceptez que l’envoi non sollicité de messages publicitaires à des adresses email de <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ou via les systèmes informatiques de <span style="color:#1E90FF;">MAKI-IMMO.COM</span>, est expressément interdit par ces Conditions. Toute utilisation frauduleuse des systèmes informatiques de <span style="color:#1E90FF;">MAKI-IMMO.COM</span> sera considérée comme une enfreinte aux Conditions présentées par ce document et à la législation sénégalaise. De telles enfreintes sont susceptibles d’exposer le responsable ou ses représentants à des poursuites civiles et pénales. </h6><br>
 <h4>9. DROITS DE PROPRIÉTÉ</h4><br>
 <h6>Le Service est protégé par les lois sur le droit d’auteur et les traités internationaux. Les contenus affichés sont protégés par le droit d’auteur en tant que travail collectif et/ou compilation, conformément aux lois sur les droits d’auteur et les conventions internationales. <br>Toute reproduction, modification, création d’œuvres dérivées ou redistribution des Sites ou des travaux collectifs est interdite.<br> Copier ou reproduire tout ou partie des sites vers un autre serveur ou un autre emplacement dans le but d’une reproduction ou redistribution postérieures est interdit.<br> Vous vous compromettez à ne pas reproduire ni copier le Contenu du Service et à respecter tous les avis concernant la protection des droits d’auteur publiés sur le Service. <br>De la même façon, vous vous compromettez à ne pas décompresser, ni désassembler, ni pratiquer de l’ingénierie inversée, ni employer aucun autre moyen afin de découvrir le code source contenu dans le Service.<br> Sans que ceci suppose une limitation aux conditions précitées, vous vous compromettez à ne pas reproduire, copier, vendre, revendre ni exploiter à des fins commerciales, aucune des parties du Service.
Bien que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne revendique pas la propriété des contenus que ses usagers placent dans les sections publiques du Service, vous accordez par là même de façon automatique, représentez et garantissez votre droit à accorder à<span style="color:#1E90FF;">MAKI-IMMO.COM</span> , une licence irrévocable, perpétuelle, non exclusive, intégralement payée, et mondiale pour la copie, d’exécution, et l’affichage du susdit Contenu et pour l’élaboration d’œuvres dérivées, ou pour l’incorporation à d’autres œuvres le dit Contenu, et à accorder et autoriser subséquemment les sous licences (via des tiers multiples).<br> Nous exigeons ces autorisations afin d’héberger et d’afficher votre contenu.
 </h6><br>
 <h4>10. DENI DE GARANTIES</h4><br>
 <h6>VOUS RECONNAISSEZ EXPRÉSSEMENT QUE L’UTILISATION DU SITEMAKI-IMMO.COM  ET DES SERVICES DÉRIVÉS SE FAIT À VOTRE RISQUE. <br>LE SITE MAKI-IMMO.COM ET LES SERVICES DÉRIVES SONT FOURNIS EN L’ÉTAT OU SUR UNE BASE DE DISPONIBILITÉ, SANS AUCUNE GARANTIE.<br> SONT EXCLUES EXPRESSÉMENT ET DANS TOUTE LA MESURE PERMISE PAR LES LOIS APPLICABLES TOUTES GARANTIES EN MATIÉRE DE VIRUS OU AUTRES COMPOSANTS DANGEREUX EN RELATION AVEC L’UTILISATION DES SERVICES OU DU SITE MAKI-IMMO.COM. Certaines juridictions et certains pays n’autorisent pas l’exclusion des garanties implicites.<br> Par conséquent, il est possible que les exclusions ci-dessus ne vous concernent pas. </h6><br>
<h4>11. LIMITES DE RESPONSABILITÉ</h4><br>
 <h6>MAKI-IMMO.COM NE POURRA EN AUCUN CAS ÊTRE TENU RESPONSABLE DES DOMMAGES DIRECTS, INDIRECTS, INCIDENTS, CONSÉQUENTS, SPÉCIAUX, EXEMPLAIRES (MÊME SI MAKI-IMMO.COM A ÉTÉ AVERTI DE LA POSSIBILITÉ DE TELS DOMMAGES), RÉSULTANT DE L’UTILISATION OU DE L’UTILISATION INCORRECTE DES SERVICES OU DU <span style="color:#1E90FF;">MAKI-IMMO.COM</span> , DE L’IMPOSSIBILITÉ D’UTILISER LES SERVICES OU LE <span style="color:#1E90FF;">MAKI-IMMO.COM</span> , INTERRUPTION, SUSPENSION OU ARRÊT TEMPORAIRE OU DÉFINITIF DES SERVICES. CES LIMITES DE RESPONSABILITÉ S’APPLIQUERONT ÉGALEMENT POUR LES DOMMAGES CAUSÉS PAR LES SERVICES OU LES BIENS REÇUS VIA (OU DONT LA PROMOTION EST ASSURÉE VIA) LES SERVICES OU LE SITE DE <span style="color:#1E90FF;">MAKI-IMMO.COM</span>, OU VIA LES LIENS PROPOSÉS PAR LE SITE <span style="color:#1E90FF;">MAKI-IMMO.COM</span> , NI PAR AUCUNE INFORMATION OU AUCUN CONSEIL REÇU VIA LES LIENS PROPOSÉS DANS LES SERVICES OU LE SITE D<span style="color:#1E90FF;">MAKI-IMMO.COM</span> .CES LIMITES DE RESPONSABILITÉ S’APPLIQUERONT DANS TOUTE LA MESURE PERMISE PAR LES LOIS EN VIGUEUR. Certaines juridictions et certains pays n’autorisent pas l’exclusion des garanties implicites. <br>Par conséquent, il est possible que les exclusions ci-dessus ne vous concernent pas. </h6><br>
 <h4>12. INDEMNITÉS</h4><br>
 <h6>Vous acceptez subséquemment d’indemniser, à vos frais, <span style="color:#1E90FF;">MAKI-IMMO.COM</span> , ses agents, ses filiales, ses associés, ses ayants droit, ses dirigeants, fournisseurs et fournisseurs de services, et employés, et de les dégager de toute responsabilité (y compris les frais judiciaires encourus par des tierces parties) relative au Contenu que vous soumettez, publiez ou distribuez via le Service, ou résultant de votre utilisation du Service, du non respect de votre part des Conditions, ou de l’infraction aux déclarations et garanties exposées dans ce document, ou si vous violez les droits d’un tiers. </h6><br>
 <h4>13. INFORMATIONS GÉNÉRALES</h4><br>
 <h6>Ces Conditions ainsi que les autres règles publiées sur <span style="color:#1E90FF;">MAKI-IMMO.COM</span> doivent être interprétées comme la base complète et exclusive d’entente et d’accord existante entre vous et <span style="color:#1E90FF;">MAKI-IMMO.COM</span>, et régira votre utilisation du Service, et abroge toute entente, proposition, négociation et tout accord antérieur entre les parties, aussi bien écrits qu’oral.
Les Conditions et la relation qui vous unit à <span style="color:#1E90FF;">MAKI-IMMO.COM</span> seront régies par les Loi en vigueur au Sénégal sans égard aux dispositions en matière de conflit des lois. Vous et <span style="color:#1E90FF;">MAKI-IMMO.COM</span> acceptez de vous soumettre à la juridiction personnelle et exclusive des tribunaux de Dakar. Le fait que <span style="color:#1E90FF;">MAKI-IMMO.COM</span> ne puisse faire exercer ou assurer l’application d’un droit ou d’une disposition contenu dans les Conditions ne constituera en aucun cas une dérogation à ce droit ou cette disposition. Si une disposition exposée dans les Conditions est considérée invalide par un tribunal compétent en la matière, les parties accordent que le tribunal devra prendre l’initiative de faire appliquer les intentions reflétées dans telle disposition, les autres dispositions exposées dans les Conditions restant pleinement effectives et applicables. <br>Vous acceptez que toute réclamation ou action légale relative à l’utilisation du Service ou à l’interprétation des Conditions devra être déposée avant un (1) an après sa déclaration, ou sera définitivement forclose.
 </h6><br>

                                                     

                                                                                                                                                                                 </h6>
                            
                            
                    </div>
                </div> 
              
  
    @endsection